@@startuml
|R|ReentrantLock
|#LightSteelBlue|SC|ReentrantLock # Sync 
|#AntiqueWhite|A|AQS
|R|
:unlock();
|A|
:release(1);
|SC|
:tryRelease(1);
note: state - 1
|A|
if(tryRelease(1)?) then
  |A|
  if(h != null && h.waitStatus != 0) then  (队列中还有后续等待节点)
  :unparkSuccessor(head_node);
  note : 唤醒后续节点  
  endif 
  :true;
  kill 
else   
  :false;
  kill
endif
@@enduml